### ISSUE TITLE
I have an error

### ISSUE THREAD

**Issue by Emi1kaTh3C4t** [danilmoh/Discord-to-Telegram#1]
When i running code i have this error:

/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(20,12): warning CS8618: Non-nullable field 'client' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(20,12): warning CS8618: Non-nullable field 'cts' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/DiscordBot.cs(19,12): warning CS8618: Non-nullable field 'client' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Data/Services/MessagesLoader.cs(26,62): warning CS8604: Possible null reference argument for parameter 'messagesList' in 'Dictionary<KeyValuePair<Chat, Chat>, Dictionary<Message, Message>> MessagesMapListConverter.ConvertToMap(List<KeyValuePair<KeyValuePair<Chat, Chat>, List<KeyValuePair<Message, Message>>>> messagesList)'. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Data/Services/MessagesLoader.cs(35,9): warning CS0162: Unreachable code detected [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/DiscordBot.cs(58,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/DiscordBot.cs(50,24): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(70,57): warning CS8602: Dereference of a possibly null reference. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(68,41): warning CS8602: Dereference of a possibly null reference. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(68,41): warning CS8602: Dereference of a possibly null reference. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(97,45): warning CS8602: Dereference of a possibly null reference. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(208,55): warning CS8604: Possible null reference argument for parameter 'name' in 'Chat.Chat(decimal id, string name)'. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
/home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs(201,16): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/home/runner/UnderstatedRichProspect/Discord-To-Telegram-Program.csproj]
Unhandled exception. System.IO.FileNotFoundException: Message file not found!
   at DiscordToTelegram.Data.Services.MessagesLoader.Load(String path) in /home/runner/UnderstatedRichProspect/Data/Services/MessagesLoader.cs:line 13
   at DiscordToTelegram.Data.Services.MessagesLoader.Load() in /home/runner/UnderstatedRichProspect/Data/Services/MessagesLoader.cs:line 41
   at DiscordToTelegram.Bots.TelegramBot..ctor() in /home/runner/UnderstatedRichProspect/Bots/TelegramBot.cs:line 23
   at DiscordToTelegram.Program.Main(String[] args) in /home/runner/UnderstatedRichProspect/Program.cs:line 8
   at DiscordToTelegram.Program.<Main>(String[] args)

**Comment by Emi1kaTh3C4t** [comment]
А ещё я заметил что ты из Саратова
